#
# include
gems: [jekyll-paginate]

#safe: false
category_dir : categories

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           date
relative_permalinks: false

# Setup
title:               Blog
tagline:             ''
description:         '记录生活工作的点滴<a href="https://twitter.com/jiehuangwei" target="_blank">@jiehuangwei</a>.'
url:                 http://www.jiehuangwei.wiki
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              jiehuangwei
  url:               https://twitter.com/jiehuangwei
  email:             jiehuangwei@gmail.com

# Custom vars
version:             1.0.0
